#springboot 这个配置文件中到低可以配置哪些东西呢

#官方的配置太多了，了解原理 一通百通
#官方推荐使用yaml
#yaml以数据为中心，以前的配置文件大多数以xml
#普通key value
#propertirs只有键值对對空格要求极其严格
#可以注入到配置类中
#server:
#  port: 8081
#
##对象
#student:
#  name: uruom
#  age: 3
#
#
##行内写法
#
#student: {name: uruom,age: 3}
#
##数组
#pets:
#  - cat
#  - dog
#  - pig

person:
  lastname: uruom
  age: ${random.int}
  happy: false
  birth: 2019/11/02
  hello: sssss
  maps: {k1: v1,k2: v2}
  lists:
    - code
    - music
    - girl
  dog:
    name: ${person.hello:hello}_kuangs
    age: 2





